## Application
server:
    port: 9080

spring:
  social:
    twitter:
      app-id: yix4Ai9xDbWBKV3yFPFGs8Nkf
      app-secret: 9rXtdeYe5v3wmGR5E96ubiXRDeWzZFgRt2ZYdgSKeQFivw0OtD
  data:
    mongodb:
      database: twitter
      host: localhost
